---
# Source: victoria-metrics-operator/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vmoperator-victoria-metrics-operator
  labels:
    app.kubernetes.io/name: victoria-metrics-operator
    app.kubernetes.io/instance: vmoperator
    helm.sh/chart: victoria-metrics-operator-0.24.1
    app.kubernetes.io/managed-by: Helm
  namespace: victoria-metrics-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  verbs:
  - create
  - get
  - update
  resources:
  - leases
