---
# Source: victoria-metrics-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: victoria-metrics-operator
  labels:
    app.kubernetes.io/name: victoria-metrics-operator
    app.kubernetes.io/instance: vmoperator
    helm.sh/chart: victoria-metrics-operator-0.24.1
    app.kubernetes.io/managed-by: Helm
  name: vmoperator-victoria-metrics-operator
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: webhook
      port: 443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: victoria-metrics-operator
    app.kubernetes.io/instance: vmoperator
  type: "ClusterIP"
