apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgresql
  labels:
    app: postgres
data:
  POSTGRES_USER: bromles
  POSTGRES_PASSWORD: '105021'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
  namespace: postgresql
  labels:
    app: postgres
data:
  init.sql: |
    CREATE DATABASE keycloak;
    CREATE USER keycloak WITH PASSWORD '105021';
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: postgresql
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgresql
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.1
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-pvc
        - mountPath: /dev/shm
          name: cache-volume
        - mountPath: /docker-entrypoint-initdb.d
          name: postgres-initdb
        envFrom:
          - configMapRef:
              name: postgres-config
        ports:
          - containerPort: 5432
            name: postgresdb
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: cache-volume
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
        - name: postgres-initdb
          configMap:
            name: postgres-initdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgresql
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: postgres
