apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-echo
spec:
  selector:
    matchLabels:
      app: test-echo
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: test-echo
    spec:
      containers:
        - name: test-echo
          image: jmalloc/echo-server
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: test-echo-service
  namespace: test-echo
  labels:
    app: test-echo
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: test-echo