apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring
spec:
  serviceScrapeNamespaceSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeSelector: {}
  nodeScrapeSelector: {}
  nodeScrapeNamespaceSelector: {}
  staticScrapeSelector: {}
  staticScrapeNamespaceSelector: {}
  replicaCount: 1
  inlineScrapeConfig: |
    - job_name: "prometheus"
        static_configs:
        - targets: ["10.254.254.254:9100"]
  remoteWrite:
    - url: "http://vminsert-vmcluster:8480/insert/0/prometheus/api/v1/write"