apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring
spec:
  serviceScrapeNamespaceSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeSelector: {}
  nodeScrapeSelector: {}
  nodeScrapeNamespaceSelector: {}
  staticScrapeSelector: {}
  staticScrapeNamespaceSelector: {}
  replicaCount: 1
  additionalScrapeConfigs:
    name: vmagent-additional-scrape-configs
    key: prometheus-additional.yaml
  remoteWrite:
    - url: "http://vminsert-vmcluster:8480/insert/0/prometheus/api/v1/write"