apiVersion: v1
kind: Namespace
metadata:
  name: meilisearch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meilisearch-config
  namespace: meilisearch
  labels:
    app: meilisearch
data:
  MEILI_MASTER_KEY: "masterKey"
  MEILI_NO_ANALYTICS: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-pvc
  namespace: meilisearch
  labels:
    app: meilisearch
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: meilisearch
spec:
  selector:
    matchLabels:
      app: meilisearch
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: meilisearch-config
          ports:
            - name: http
              containerPort: 7700
          volumeMounts:
            - mountPath: /meili_data
              name: meili-data
      volumes:
        - name: meili-data
          persistentVolumeClaim:
            claimName: meilisearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch-service
  namespace: meilisearch
  labels:
    app: meilisearch
spec:
  type: LoadBalancer
  ports:
    - port: 7070
      targetPort: 7070
  selector:
    app: meilisearch
