apiVersion: v1
kind: Namespace
metadata:
  name: meilisearch
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meilisearch-config
  namespace: meilisearch
  labels:
    app: meilisearch
data:
  MEILI_MASTER_KEY: "veryLongAndVerySecretMasterKey"
  MEILI_NO_ANALYTICS: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-pvc
  namespace: meilisearch
  labels:
    app: meilisearch
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: meilisearch
spec:
  selector:
    matchLabels:
      app: meilisearch
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: meilisearch-config
          ports:
            - name: http
              containerPort: 7700
          volumeMounts:
            - mountPath: /meili_data
              name: meili-data
      volumes:
        - name: meili-data
          persistentVolumeClaim:
            claimName: meilisearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch-service
  namespace: meilisearch
  labels:
    app: meilisearch
spec:
  type: ClusterIP
  ports:
    - port: 7700
  selector:
    app: meilisearch
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: meilisearch-route
  namespace: meilisearch
spec:
  parentRefs:
  - name: global-gateway
    namespace: global-gateway
    sectionName: global-http-gw
  rules:
  - matches:
    - path:
        value: /meilisearch
    backendRefs:
    - name: meilisearch-service
      port: 7700