---
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-6.58.6
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "10.0.2"
    app.kubernetes.io/managed-by: Helm
data:
  plugins: https://github.com/VictoriaMetrics/grafana-datasource/releases/download/v0.2.1/victoriametrics-datasource-v0.2.1.zip;victoriametrics-datasource
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [plugins]
    allow_loading_unsigned_plugins = victoriametrics-datasource
    [server]
    domain = ''
    enable_gzip = true
    enforce_domain = false
    root_url = http://localhost:3000/monitoring/grafana
    serve_from_sub_path = true
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - allowUiUpdates: true
      disableDeletion: false
      editable: true
      folder: ""
      name: default
      options:
        path: /var/lib/grafana/dashboards/default
      orgId: 1
      type: file
      updateIntervalSeconds: 10
  download_dashboards.sh: |
    #!/usr/bin/env sh
    set -euf
    mkdir -p /var/lib/grafana/dashboards/default
