apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap-dashboard-provider.yaml
- configmap.yaml
- dashboards-json-configmap.yaml
- deployment.yaml
- httproute.yaml
- pvc.yaml
- role.yaml
- rolebinding.yaml
- secret.yaml
- service.yaml
- serviceaccount.yaml
