apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: keycloak
  namespace: kube-system
spec:
  repo: https://codecentric.github.io/helm-charts
  chart: keycloak
  targetNamespace: keycloak
  set:
    image.tag: "20.0"
    service.type: "LoadBalancer"
    postgresql.enabled: "false"
    postgresql.postgresqlUsername: "bromles"
    postgresql.postgresqlPassword: "105021"
  valuesContent: |-
    extraEnv: |
      - name: KEYCLOAK_USER
        value: "bromles"
      - name: KEYCLOAK_PASSWORD
        value: "105021"
      - name: DB_VENDOR
        value: postgres
      - name: DB_ADDR
        value: "192.168.5.202"
      - name: DB_PORT
        value: "5432"
