apiVersion: v1
kind: Namespace
metadata:
  name: garage
  labels: 
    istio-injection: enabled
---
# Source: garage/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: garage
  namespace: garage
  labels:
    app.kubernetes.io/name: garage
---
# Source: garage/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: garage-rpc-secret
  namespace: garage
  labels:
    app.kubernetes.io/name: garage
type: Opaque
data:
  rpcSecret: "N2RhODA4MTNkOTY0NTNhYTY0MWZmNjI2NzFlOGQzMzg4ZjRjYjllODkyYTM1YzcyNTIzYmY0MjIzMzdmN2JiMw=="
---
# Source: garage/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
  namespace: garage
data:
  garage.toml: |-
    metadata_dir = "/mnt/meta"
    data_dir = "/mnt/data"
    
    replication_mode = "3"
    
    compression_level = 10
    
    rpc_bind_addr = "[::]:3901"
    # rpc_secret will be populated by the init container from a k8s secret object
    rpc_secret = "__RPC_SECRET_REPLACE__"
    
    [kubernetes_discovery]
    namespace = "garage"
    service_name = "garage"
    skip_crd = false
    
    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"
    root_domain = ".s3.garage.tld"
    
    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.garage.tld"
    
    [admin]
    api_bind_addr = "[::]:3903"
    admin_token = "ev6u6ibUndGtXdEh0SPH1VbLy52a7V5VrT1H4f8Z+E0="
---
# Source: garage/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-crds-default-release-name
  namespace: garage
  labels:
    app.kubernetes.io/name: garage
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups: ["deuxfleurs.fr"]
  resources: ["garagenodes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Source: garage/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-crds-for-default-release-name
  namespace: garage
  labels:
    app.kubernetes.io/name: garage
subjects:
- kind: ServiceAccount
  name: garage
  namespace: default
roleRef:
  kind: ClusterRole
  name: manage-crds-default-release-name
  apiGroup: rbac.authorization.k8s.io
---
# Source: garage/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: garage
  labels:
    app.kubernetes.io/name: garage
spec:
  type: LoadBalancer
  ports:
    - port: 3900
      targetPort: 3900
      protocol: TCP
      name: s3-api
    - port: 3902
      targetPort: 3902
      protocol: TCP
      name: s3-web
    - port: 3903
      targetPort: 3903
      protocol: TCP
      name: admin
  selector:
    app.kubernetes.io/name: garage
---
# Source: garage/templates/workload.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: garage
  namespace: garage
  labels:
    app.kubernetes.io/name: garage
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: garage
  replicas: 3
  serviceName: garage
  template:
    metadata:

      annotations:
        checksum/config: 148e6e25b7e47daa1f74287aeefa020bad54bc8bc48346936c6f4c8067658dcd
      labels:
        app.kubernetes.io/name: garage
    spec:
      serviceAccountName: garage
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      initContainers:
        # Copies garage.toml from configmap to temporary etc volume and replaces RPC secret placeholder
        - name: garage-init
          image: "busybox:stable"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "sed \"s/__RPC_SECRET_REPLACE__/$RPC_SECRET/\" /mnt/garage.toml > /mnt/etc/garage.toml"]
          env:
            - name: RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: garage-rpc-secret
                  key: rpcSecret
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: configmap
              mountPath: /mnt/garage.toml
              subPath: garage.toml
            - name: etc
              mountPath: /mnt/etc
      containers:
        - name: garage
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          image: "dxflrs/garage:v0.9.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3900
              name: s3-api
            - containerPort: 3902
              name: web-api
            - containerPort: 3903
              name: admin
          volumeMounts:
            - name: meta
              mountPath: /mnt/meta
            - name: data
              mountPath: /mnt/data
            - name: etc
              mountPath: /etc/garage.toml
              subPath: garage.toml
          # TODO
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3900
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3900
          resources:
            {}
      volumes:
        - name: configmap
          configMap:
            name: garage-config
        - name: etc
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: meta
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: "500Mi"
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: "2000Mi"
