apiVersion: v1
appVersion: 0.35.
description: Victoria Metrics Operator
home: https://github.com/VictoriaMetrics/operator
name: victoria-metrics-operator
sources:
- https://github.com/VictoriaMetrics/helm-charts
- https://github.com/VictoriaMetrics/operator
version: 0.24.1
