apiVersion: v1
kind: Namespace
metadata:
  name: harbor
  labels:
    istio-injection: enabled
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: harbor
  namespace: kube-system
spec:
  repo: https://helm.goharbor.io
  chart: harbor
  targetNamespace: harbor
  set:

  valuesContent: |
