apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hubble-ui-route
  namespace: kube-system
spec:
  parentRefs:
  - name: global-gateway
    namespace: global-gateway
    sectionName: global-http-gw
  rules:
  - matches:
    - path:
        value: /hubble-ui
    backendRefs:
    - name: hubble-ui
      port: 80
