services:
  nexus:
    image: bromles/nexus3:latest
    container_name: nexus
    # environment:
    #   # Run this under http://localhost:8081/nxrm/
    #   NEXUS_CONTEXT: 'nxrm'
    volumes:
      - nexus-data:/nexus-data
    ports:
      - 8081:8081

volumes:
  nexus-data: