apiVersion: v1
kind: Namespace
metadata:
  name: nexus
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-config
  namespace: nexus
  labels:
    app: nexus
data:
  NEXUS_CONTEXT: "nexus"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: nexus
  labels:
    app: nexus
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: bromles/nexus3:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: nexus-config
          ports:
            - name: http
              containerPort: 8081
          volumeMounts:
            - mountPath: /
              name: nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-svc
  namespace: nexus
  labels:
    app: nexus
spec:
  type: ClusterIP
  ports:
    - port: 8081
  selector:
    app: nexus
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: nexus-route
  namespace: nexus
spec:
  parentRefs:
  - name: global-gateway
    namespace: global-gateway
    sectionName: global-http-gw
  rules:
  - matches:
    - path:
        value: /nexus
    backendRefs:
    - name: nexus-svc
      port: 8081