apiVersion: v1
kind: Namespace
metadata:
  name: portainer
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: portainer
  namespace: kube-system
spec:
  repo: https://portainer.github.io/k8s/
  chart: portainer
  targetNamespace: portainer
  set:
    service.type: "ClusterIP"
    tls.force: "true"
    ingress.enabled: "true"
    ingress.ingressClassName: "nginx"
    ingress.annotations.nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.hosts[0].host: "portainer.rock-5b.local"
    ingress.hosts[0].paths[0].path: "/"
