# Example of PostgreSQL cluster
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-main-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: main-cluster
  namespace: cnpg-main-cluster
spec:
  instances: 2

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: "unsupervised"

  postgresql:
    pg_hba:
      - host all all all scram-sha-256
  
  bootstrap:
    initdb:
      database: bromles
      owner: bromles
      encoding: 'UTF8'
      postInitSQL:
        - alter user bromles with password '105021';
        - alter user bromles with superuser;
        - create user keycloak with encrypted password '105021';
        - create database keycloak;
        - alter database keycloak owner to keycloak;

  # Require 25Gi of space
  storage:
    storageClass: longhorn
    size: 25Gi

  monitoring:
   enablePodMonitor: true