# Example of PostgreSQL cluster
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-main-cluster
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: main-cluster-app-user
  namespace: cnpg-main-cluster
data:
  password: MTA1MDIx
  username: YnJvbWxlcw==
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: main-cluster
  namespace: cnpg-main-cluster
spec:
  instances: 2

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: "unsupervised"

  enableSuperuserAccess: true
  superuserSecret:
    name: main-cluster-app-user

  postgresql:
    pg_hba:
      - host all all all scram-sha-256
  
  bootstrap:
    initdb:
      database: bromles
      owner: bromles
      encoding: 'UTF8'
      secret:
        name: main-cluster-app-user

  # Require 25Gi of space
  storage:
    storageClass: longhorn
    size: 25Gi

  monitoring:
   enablePodMonitor: true